project_name: frontdoor
builds:
  - main: ./
    ldflags:
      - -s -w -X main.version={{.Version}}
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64